_BASE_: "../base-rcnn-fpn.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("bdd100k_val",)
  BATCH_COMPONENTS: ("labeled_strong", )
EMA:
  ENABLED: False
SOLVER:
  STEPS: (2999,)
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 100
OUTPUT_DIR: "output/bdd100k/bdd100k_warmup_strongaug_imagenet/"