_BASE_: "../base-rcnn-fpn.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("sim10k_cars_train",)
  TEST: ("cityscapes_cars_val",)
  BATCH_COMPONENTS: ("labeled_strong", )
EMA:
  ENABLED: False
SOLVER:
  STEPS: (2999,)
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 100
OUTPUT_DIR: "output/sim10k/sim10k_warmup_strongaug_imagenet/"