_BASE_: "./base-rcnn-cityscapes.yaml"
MODEL:
  WEIGHTS: "output/cityscapes/cityscapes_da2od_strongaug_imagenet//cityscapes_foggy_val_model_best.pth"
EMA:
  ENABLED: True
DA:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False
    SOFT_ROIH_CLS_ENABLED: True
    SOFT_OBJ_ENABLED: True
    SOFT_ROIH_REG_ENABLED: True
    SOFT_RPN_REG_ENABLED: True
  ALIGN:
    IMG_ALIGN_ENABLED: True
    INS_ALIGN_ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_COMPONENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
SOLVER:
  STEPS: (14999,)
  MAX_ITER: 15000
  BACKWARD_AT_END: True
OUTPUT_DIR: "output/cityscapes/cityscapes_da2od_best/"